---
# https://pre-commit.com

- id: mark-toc
  name: mark-toc
  description: This hook generates tables of contents in Markdown files.
  entry: mark-toc --pre-commit
  language: python
  pass_filenames: true
  types: [file, markdown]
